### PR TITLE
harshgarg28 completed Subtask-3

### PR DESCRIPTION
**Pull request by harshgarg28**
completed subtask 3

### CODE REVIEW

**Comment by Elemento24** [comment]
@harshgarg28 You have cut Sir's name and Solve the Merge Conflicts

**Comment by harshgarg28** [comment]
is it correct now

**Comment by Elemento24** [comment]
@harshgarg28 Solve the Merge Conflicts again

**Comment by harshgarg28** [comment]
sir, please check

**Comment by pradhuman1** [comment]
@harshgarg28 resolve conflicts!!

**Pull request merged**
