### PR TITLE
bipulkmr-crypto Subtask 2 done

### PR DESCRIPTION
**Pull request by bipulkmr-crypto**
Completed Subtask 2 and updated text file

### CODE REVIEW

**Comment by bipulkmr-crypto** [comment]
Thanks GeekHaven for the support

**Comment by 2802harsh** [comment]
@bipulkmr-crypto pls resolve the conflicts asap ; I will merge your PR next. In case you can't do it right away do comment and let us know

**Comment by bipulkmr-crypto** [comment]
> @bipulkmr-crypto pls resolve the conflicts asap ; I will merge your PR next. In case you can't do it right away do comment and let us know

Done Sir

**Comment by 2802harsh** [comment]
@bipulkmr-crypto  you should not delete what's already there. Just add something you want. Please make necessary changes.

**Comment by bipulkmr-crypto** [comment]
Sir made nessecary changes

**Pull request merged**
