### PR TITLE
raviutsav completed Subtask-3

### PR DESCRIPTION
**Pull request by raviutsav**

### CODE REVIEW

**Comment by GhostFoxSledgehammer** [comment]
bhai kya kar raha yaar

**Comment by raviutsav** [comment]
sir, maine kuch gadbad kar diya?

**Comment by raviutsav** [comment]
mere se kuch galt ho gya tha, toh main PR delete kar diya.

**Comment by raviutsav** [comment]
Subtask-2 ke branch mein, galti se maine yeh subtask-3 ka command put kar
diya tha git pull --rebase https://github.com/Elemento24/FunWithBranches.git
Subtask-3,

**Pull request closed without merging**
