### PR TITLE
kartiks1309 completed Subtask-3

### PR DESCRIPTION
**Pull request by kartiks1309**
accept my PR, no conflicts

### CODE REVIEW

**Comment by Elemento24** [comment]
@kartiks1309 Why so soon :joy: , go ahead solve them

**Comment by kartiks1309** [comment]
ya sir, trick not gonna work, gotta resolve XD

**Comment by kartiks1309** [comment]
done :)

**Comment by kartiks1309** [comment]
@Elemento24 sir don't merge this PR, I've made new pull request

**Pull request closed without merging**
