### PR TITLE
HariPrasath-3 completed subtask-2

### PR DESCRIPTION
**Pull request by HariPrasath-3**

### CODE REVIEW

**Comment by HariPrasath-3** [comment]
@Elemento24 I Resolved the conflict

**Comment by pradhuman1** [comment]
@HariPrasath-3 please resolve conflicts

**Comment by pradhuman1** [comment]
@HariPrasath-3 resolve conflicts!!

**Comment by HariPrasath-3** [comment]
@pradhuman1 Sir I resolved the conflicts

**Pull request merged**
