### PR TITLE
21-kunal Completed subtask-2

### PR DESCRIPTION
**Pull request by 21-kunal**
Subtask-2 completed

### CODE REVIEW

**Comment by Elemento24** [comment]
@21-kunal Merge Conflicts

**Comment by 21-kunal** [comment]
I had Completed the conflicts.

**Comment by 21-kunal** [comment]
Resolve the conflicts

**Comment by 21-kunal** [comment]
I had fixed the conflicts.

**Comment by 21-kunal** [comment]
I had fixed the conflicts.

**Pull request merged**
